const CLASSES = new Map([

    // Free Classes
    [1,  { name: "Cactus", cost: 0, level: 0 }],
    [4,  { name: "Skeleton", cost: 0, level: 0 }],
    [7,  { name: "Enderman", cost: 0, level: 0 }],
    [18, { name: "Horse", cost: 0, level: 0 }],
    [26, { name: "Rabbit", cost: 0, level: 0 }],
    [20, { name: "Squid", cost: 0, level: 0 }],
    [21, { name: "Spider", cost: 0, level: 0 }],
    [30, { name: "Pig", cost: 0, level: 0 }],
    [31, { name: "Blaze", cost: 0, level: 0 }],
    [33, { name: "Wither", cost: 0, level: 0 }],
    [35, { name: "Creeper", cost: 0, level: 0 }],
    [38, { name: "Present", cost: 0, level: 0, vaulted: true }],
    [43, { name: "Dweller", cost: 0, level: 0, vaulted: true }],
    [44, { name: "Zombie", cost: 0, level: 0 }],
    [45, { name: "Silverfish", cost: 0, level: 0 }],
    [49, { name: "Villager", cost: 0, level: 0 }],
    [58, { name: "FlintAndSteel", cost: 0, level: 0 }],
    [64, { name: "LargeFern", cost: 0, level: 0 }],
    [67, { name: "Fisherman", cost: 0, level: 0 }],

    // Token Classes
    [2,  { name: "TNT", cost: 350, level: 0 }],
    [5,  { name: "Ninja", cost: 1000, level: 0 }],
    [9,  { name: "Chicken", cost: 400, level: 0 }],
    [12, { name: "DarkSethBling", cost: 800, level: 0 }],
    [14, { name: "SnowGolem", cost: 800, level: 0 }],
    [17, { name: "Sheep", cost: 550, level: 0 }],
    [24, { name: "Bunny", cost: 450, level: 0 }],
    [25, { name: "ButterBro", cost: 1200, level: 0, vaulted: true }],
    [28, { name: "Steve", cost: 850, level: 0 }],
    [29, { name: "Notch", cost: 1000, level: 0 }],
    [32, { name: "Potato", cost: 750, level: 0 }],
    [34, { name: "Ocelot", cost: 250, level: 0 }],
    [36, { name: "Noteblock", cost: 800, level: 0 }],
    [37, { name: "EnchantTable", cost: 350, level: 0, vaulted: true }],
    [42, { name: "Star", cost: 850, level: 0, vaulted: true }],
    [46, { name: "Anvil", cost: 700, level: 0 }],
    [47, { name: "Summoner", cost: 525, level: 0 }],
    [53, { name: "Vampire", cost: 800, level: 0 }],
    [55, { name: "Bee", cost: 425, level: 0 }],
    [57, { name: "Hunter", cost: 500, level: 0 }],
    [59, { name: "WitherSkeleton", cost: 1500, level: 0 }],
    [71, { name: "Wolf", cost: 400, level: 0 }],
    [68, { name: "BrewingStand", cost: 350, level: 0 }],
    [72, { name: "Parrot", cost: 800, level: 0 }],

    // Level Classes
    [51, { name: "ZombiePigman", cost: 0, level: 3 }],
    [13, { name: "Witch", cost: 0, level: 5 }],
    [50, { name: "ZombieVillager", cost: 0, level: 10 }],
    [54, { name: "Ice", cost: 0, level: 15 }],
    [56, { name: "Jeb", cost: 0, level: 20 }],
    [60, { name: "Shulker", cost: 0, level: 25 }],
    [63, { name: "Cloud", cost: 0, level: 30 }],
    [69, { name: "Guardian", cost: 0, level: 30, vaulted: true }],

    // Donor Classes
    [3,  { name: "Enderdragon", rank: "VIP" }],
    [6,  { name: "IronGolem", rank: "VIP" }],
    [8,  { name: "Ghast", rank: "VIP" }],
    [10, { name: "Slime", rank: "VIP" }],
    [11, { name: "PiglinBrute", rank: "VIP" }],
    [15, { name: "Bat", rank: "VIP" }],
    [16, { name: "SethBling", rank: "VIP" }],
    [19, { name: "Melon", rank: "VIP" }],
    [22, { name: "Mooshroom", rank: "VIP" }],
    [23, { name: "Herobrine", rank: "VIP" }],
    [41, { name: "Wizard", rank: "VIP" }],
    [48, { name: "MagmaCube", rank: "VIP" }],
    [61, { name: "Bedrock", rank: "VIP" }],
    [62, { name: "Firework", rank: "VIP" }],
    [65, { name: "Vindicator", rank: "VIP", vaulted: true }],
    [66, { name: "Fade", rank: "VIP" }],
    [70, { name: "Endermite", rank: "VIP" }],

    // Holiday Classes
    [101, { name: "Elf", cost: 0, level: 0, vaulted: true }],
    [102, { name: "GingerBreadMan", cost: 0, level: 0, vaulted: true }],
    [103, { name: "Santa", cost: 0, level: 0, vaulted: true }],
    [104, { name: "GrimReaper", cost: 0, level: 0, vaulted: true }],
    [105, { name: "Freddy", cost: 0, level: 0, vaulted: true }]
]);

export { CLASSES };